// import type { NextPage } from 'next'
// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/index.module.scss'

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>404 n't fun =3</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon-2.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1>404 | PAGE NOT FOUND</h1>
//         <p>Hế lô ! Zo quéo căm...</p>
//       </main>

//       <footer className={styles.footer}>
//         <p>Made with{' '}
//           <Image src="/heart.jpg" alt="" width={24} height={14} />
//           {' '} by a coder
//         </p>
//       </footer>
//     </div>
//   )
// }

// export default Home
